// GENERATED FILE - do not edit netlify/edge-functions/api-sources.js by hand.
// Source template: netlify-build/templates/api-sources.template.js
// Regenerated by scripts/fetch-laws.mjs on every build.

const LAW_REGISTRY = [
  {
    abbreviation: "BetrVG",
    name_de: "Betriebsverfassungsgesetz",
    name_en: "Works Constitution Act",
    source_url: "https://www.gesetze-im-internet.de/betrvg/",
  },
  {
    abbreviation: "BDSG",
    name_de: "Bundesdatenschutzgesetz",
    name_en: "Federal Data Protection Act",
    source_url: "https://www.gesetze-im-internet.de/bdsg_2018/",
  },
];

const SECTION_COUNTS = {"BetrVG":148,"BDSG":86};

export default async () => {
  const laws = LAW_REGISTRY.map((entry) => {
    const count = SECTION_COUNTS[entry.abbreviation];
    const loaded = typeof count === "number";
    return {
      abbreviation: entry.abbreviation,
      name_de: entry.name_de,
      name_en: entry.name_en,
      source_url: entry.source_url,
      loaded,
      section_count: loaded ? count : null,
    };
  });
  return new Response(JSON.stringify({ laws }), {
    headers: { "content-type": "application/json" },
  });
};

export const config = { path: "/api/sources" };
